### ISSUE TITLE
[V2] - Closing roadmap

### ISSUE THREAD

**Issue by semoal** [rematch/rematch#792]
Hi guys, 

You can test all the changes installing the next version on all the other packages:
```
npx update-by-scope -t next @rematch
```

## Todos before stable
- [x] Improve examples folder with typescript codebases (they're the most conflictive), we should keep also the js examples. #812  
- [x] Improve documentation about typescript plugins #817 
- [x] Try to remove @ts-ignore on codebases as much as we can. #816 
- [x] Improve testing suite as much as we can, to avoid some regression with typings.
- [x] Check compatibility with typescript 4.x.x
- [x] Probably we should take a look to destructuring on effects dispatch param, I have a large codebase where i'm destructuring that, and with the next branch, all exploded. If we can't recover this, we should write a codemod for helping people to migrate, I don't expected people will use version 2.0.0 if we break all his models and they need to rename 250k variables.. #811 
- [x] Fix select plugin compatibility with typescript
- [x] Rollback meta parameter from action

> To help with this, just comment on this issue creating other issue with his title, so i'll reference that issue from here.

> **Probably the stable release will be at the first of Q4.**

We introduced some changes to our V2 version:

## Internal Changes
- reorganized directories and files to support monorepo structure
- changed building scripts to use tsdx and one common tsconfig as a base
- changed input of validate method - it now accepts a function returning a list of validations instead of accepting directly a list, to avoid doing computation in production since it's not needed as errors won't be thrown anyway
- changed behaviour of the validation method - it now collects and throws all errors, not just the first one
- changed the default name assigned to stores from a number to Rematch Store ${number} for clarity
- removed possibility for plugins to include any plugins in their configuration as it might introduce duplication etc. It is easy enough to describe in a plugin's readme that some other plugin is required first.
- removed onInit hook as there is really no use case for it
- added new hooks for plugins - onReducer and onRootReducer
- improved typings
- changed dispatch and effects to be internal part of the core code instead of plugins - it makes it easier to reason about the code, to write plugins and to declare types, both for the core and plugins

## Size diff

1.4.0 version:
![stable](https://badgen.net/bundlephobia/min/@rematch/core)

Latest **next** version:
![next](https://badgen.net/bundlephobia/min/@rematch/core@next)

## Troubleshoots

https://rematch.netlify.app/#/troubleshoots

**Comment by haikyuu** [comment]
@semoal Thanks a lot for your great work on this library. I've created an issue to track typescript extraction as it seems to be broken even in the `next` version. #797

**Comment by semoal** [comment]
We'll release probably the stable the next Tuesday. Be tuned 👍🏻

**Comment by puckey** [comment]
I tested the latest version on our codebase and it works perfectly - especially the new typescript types are very much appreciated. Thanks!

**Comment by simonasdev** [comment]
finally there are 0 type errors in my codebase :D thank you so much, can't wait for the stable release!

**Comment by guopingxiao** [comment]
> We'll release probably the stable the next Tuesday. Be tuned 👍🏻

now is 2021，we are expecting the next version~

**Comment by semoal** [comment]
> > We'll release probably the stable the next Tuesday. Be tuned 👍🏻
> 
> now is 2021，we are expecting the next version~

We're working on major documentation update with a new technology, all the links reviewed etc... so probably we'll delay the stable till end of month. Anyways you can use @next version because probably we wont change the API, so the migration from next to latest will be just doing a npm install :)

Hope this is not a problem for anyone, i just want to get the max adoption to this new version and I want to improve the documentation as much as I can. 

Kind regards and happy new year to everyone 🎂

**Comment by semoal** [comment]
## Officially Rematch Version 2 has been released 🥳 

Thanks to everyone for the amazing support and the incredible feedback you provided. 

@tianzhich @pjamrozowicz this version couldn't be possible without you.

I want to introduce also the new website that we built in a few days for doing this release possible: [https://rematchjs.org](https://rematchjs.org).

Feel free to open any issue you find with the latest version and we'll be happy to help!!

ps: we have now a blog i posted there what changes we introduced to Rematch https://rematchjs.org/blog/welcome

**Comment by pjamrozowicz** [comment]
Sorry for reopening this issue just to say this but congrats @semoal! 🥳 I'm so glad @tianzhich picked up the work I've started to refactor and improve the codebase and that you managed to finish it up!

New docs look great 👍
