### ISSUE TITLE
2.1.0 - Roadmap

### ISSUE THREAD

**Issue by semoal** [rematch/rematch#896]
Hello folks 👋 !

Already passed 3 months from the latest release of Rematch and I think we got a cool roadmap for the next release:

### Bug fixes

- [x] #893 - Typescript connect() fails about circular references
- [X] #894 - #902 Improve Typescript dispatch.reducer inference and effects
- [x] #870 - this.reducer isn't typed correctly, probably this one since it's complex to fix, we can go with any.
- [X] #892 - init() models also accepts Partial<RootModel>, this can be used in conjuntion with store.addModel() for dynamic adding models
- [x] #907 - Fix return error of loading plugin
- [x] #912 - Upgraded 4.1.2 to 4.3.X of TypeScript and never is returned when calling effect-reducer with same name 

### New features

- [X] #922  - Create an option on loading plugin to handle the status of the promise (success-loading-error), super useful for building UI's
- [x] #874 - Release and complete @rematch/typed-state
- [x] #897  - @rematch/immer peerDependency update immer to >9

### Chores/Refactor

- [ ] #880 - Reduce bundle size even more =)
- [X] #899 - Improve development experience for new contributors, now pre-commit hook it's faster than ever

### Docs

- [x] #908 - Add shiki-twoslash to Rematch docs

### Dev ops
- [x] #895 - Nightly builds with Typescript@next -> [![Rematch Nightly Suite with TypeScript@next](https://github.com/rematch/rematch/actions/workflows/next-typescript-ci.yml/badge.svg)](https://github.com/rematch/rematch/actions/workflows/next-typescript-ci.yml)
- [ ] #881 - Tracking performance regressions

### Book release

- [ ] Develop a new page to promote the book

> I can't say any deadline yet, since my current workload it's totally full on the book and my current work, but I'll comment on this thread with any update.

**Comment by tianzhich** [comment]
Great job mate, it's very clear what we need to do next period. I'll try to fix these issues.

**Comment by tianzhich** [comment]
I created a branch called `improve-typing` which related to all the fixes and improvements about rematch types. We can set it as a target branch before release v2.1.0. Anyone can also checkout the branch from here to avoid the second revision of the same place.

**Comment by semoal** [comment]
🥳 I'm happy to announce that 2.1.0 has been released.

It's such a solid version where we released mostly fixes for TypeScript which will improve your development experience a lot.

Also, includes a cool feature to @rematch/loading where passing `{ type: 'full' }` to the plugin opts you will have Error's of your promise, success and loading, such a pleasure to build UI with this pattern.

Also we released @rematch/typed-state, useful for these people who uses JavaScript codebases and want an extra step in their state.

Hope you enjoy this version, and feel free to open an issue if you find something not working properly.

Cheers 🥂
